### PR TITLE
Prevent send chunks when it is finished

### PR DESCRIPTION
**Pull request by luizmacfilho**
When the online event is dispatched, it's trying to send chunks again even the success dispatch has already been called and the file is already uploaded.

### CODE REVIEW

**Comment by dylanjha** [comment]
@luizmacfilho thank you for the PR! I want to to get some small changes together for a release soon and I don't see any reason that this would not be included.

Thank you!

**Comment by dylanjha** [comment]
@luizmacfilho we added some more tests to master (#36) - would you mind updating your branch with upstream master please? [instructions](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)

I tried to but I'm seeing permission denied when I try to push to your repo (if you would like me to handle that, there should be a box you can check on the PR which will allow maintainers to edit your branch)

**Comment by luizmacfilho** [comment]
Done @dylanjha

**Comment by mmcc** [comment]
Thank you, @luizmacfilho!

**Pull request merged**
