### PR TITLE
externalize retry codes

### PR DESCRIPTION
**Pull request by DmitryKashinskyAtSpark**
DONE:
 - updated `readme.md` to reflect actual option names
 - externalized `retryCodes` for better control over retries

### CODE REVIEW

**Review by jaredsmith — APPROVED** [review]
Looks great!

**Comment by jaredsmith** [comment]
Thanks @DmitryKashinskyAtSpark for doing this!  I'm going to go ahead and merge now, and cut a new UpChunk release later today.

**Comment by jaredsmith** [comment]
Thanks again @DmitryKashinskyAtSpark -- version 2.6.0 is now live with your changes.

**Comment by DmitryKashinskyAtSpark** [comment]
> Thanks again @DmitryKashinskyAtSpark -- version 2.6.0 is now live with your changes.

Thanks @jaredsmith!

**Pull request merged**
