### PR TITLE
Bump for v2.2.1

### PR DESCRIPTION
**Pull request by james-mux**
- Fix an issue when chunks are sent again after the success dispatch has already been called
- Bum to v2.2.1

### CODE REVIEW

**Comment by dylanjha** [comment]
welp:

```
Run yarn install --frozen-lockfile
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/parse-headers/-/parse-headers-2.0.3.tgz: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/upchunk/upchunk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by dylanjha** [comment]
kicked off a new CI build in GH actions

**Comment by james-mux** [comment]
Thanks!

**Review by dylanjha — APPROVED** [review]
LGTM, feel free to merge and create a new release! (might want to update README_INTERNAL.md on this branch too)

**Comment by james-mux** [comment]
@dylanjha internal readme added as well - if you're able to give me a final 👍  i'll ship

**Review by jsanford8 — APPROVED** [review]

**Pull request merged**
